package com.crivero.web.service.employee;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.8
 * 2016-10-26T13:22:29.665+02:00
 * Generated source version: 2.7.8
 * 
 */
@WebService(targetNamespace = "http://employee.service.web.crivero.com", name = "employeeServiceWSOPortType")
@XmlSeeAlso({ObjectFactory.class, com.crivero.web.service.employee.dto.xsd.ObjectFactory.class})
public interface EmployeeServiceWSOPortType {

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "urn:getEmployees", output = "urn:getEmployeesResponse")
    @RequestWrapper(localName = "getEmployees", targetNamespace = "http://employee.service.web.crivero.com", className = "com.crivero.web.service.employee.GetEmployees")
    @WebMethod(action = "urn:getEmployees")
    @ResponseWrapper(localName = "getEmployeesResponse", targetNamespace = "http://employee.service.web.crivero.com", className = "com.crivero.web.service.employee.GetEmployeesResponse")
    public java.util.List<com.crivero.web.service.employee.dto.xsd.Employee> getEmployees();

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "urn:removeEmployee", output = "urn:removeEmployeeResponse")
    @RequestWrapper(localName = "removeEmployee", targetNamespace = "http://employee.service.web.crivero.com", className = "com.crivero.web.service.employee.RemoveEmployee")
    @WebMethod(action = "urn:removeEmployee")
    @ResponseWrapper(localName = "removeEmployeeResponse", targetNamespace = "http://employee.service.web.crivero.com", className = "com.crivero.web.service.employee.RemoveEmployeeResponse")
    public java.lang.String removeEmployee(
        @WebParam(name = "id", targetNamespace = "")
        java.lang.String id
    );

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "urn:insertEmployee", output = "urn:insertEmployeeResponse")
    @RequestWrapper(localName = "insertEmployee", targetNamespace = "http://employee.service.web.crivero.com", className = "com.crivero.web.service.employee.InsertEmployee")
    @WebMethod(action = "urn:insertEmployee")
    @ResponseWrapper(localName = "insertEmployeeResponse", targetNamespace = "http://employee.service.web.crivero.com", className = "com.crivero.web.service.employee.InsertEmployeeResponse")
    public java.lang.String insertEmployee(
        @WebParam(name = "id", targetNamespace = "")
        java.lang.String id,
        @WebParam(name = "name", targetNamespace = "")
        java.lang.String name,
        @WebParam(name = "address", targetNamespace = "")
        java.lang.String address
    );
}
