package org.wso2.ws.dataservice;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.8
 * 2016-10-26T13:20:43.277+02:00
 * Generated source version: 2.7.8
 * 
 */
@WebService(targetNamespace = "http://ws.wso2.org/dataservice", name = "com.crivero.data.servicePortType")
@XmlSeeAlso({ObjectFactory.class})
public interface ComCriveroDataServicePortType {

    @WebMethod(action = "urn:insertEmployee")
    @Action(input = "urn:insertEmployee")
    @Oneway
    @RequestWrapper(localName = "insertEmployee", targetNamespace = "http://ws.wso2.org/dataservice", className = "org.wso2.ws.dataservice.InsertEmployee")
    public void insertEmployee(
        @WebParam(name = "id", targetNamespace = "http://ws.wso2.org/dataservice")
        java.lang.String id,
        @WebParam(name = "name", targetNamespace = "http://ws.wso2.org/dataservice")
        java.lang.String name,
        @WebParam(name = "address", targetNamespace = "http://ws.wso2.org/dataservice")
        java.lang.String address
    );

    @WebMethod(action = "urn:deleteEmployeeById")
    @Action(input = "urn:deleteEmployeeById")
    @Oneway
    @RequestWrapper(localName = "deleteEmployeeById", targetNamespace = "http://ws.wso2.org/dataservice", className = "org.wso2.ws.dataservice.DeleteEmployeeById")
    public void deleteEmployeeById(
        @WebParam(name = "id", targetNamespace = "http://ws.wso2.org/dataservice")
        java.lang.String id
    );

    @WebMethod(action = "urn:getEmployees")
    @Action(input = "urn:getEmployees", output = "urn:getEmployeesResponse", fault = {@FaultAction(className = DataServiceFault_Exception.class, value = "urn:getEmployeesDataServiceFault")})
    @RequestWrapper(localName = "getEmployees", targetNamespace = "http://ws.wso2.org/dataservice", className = "org.wso2.ws.dataservice.GetEmployees")
    @ResponseWrapper(localName = "empleados", targetNamespace = "http://ws.wso2.org/dataservice", className = "org.wso2.ws.dataservice.Empleados")
    @WebResult(name = "employee", targetNamespace = "http://ws.wso2.org/dataservice")
    public java.util.List<org.wso2.ws.dataservice.Employee> getEmployees() throws DataServiceFault_Exception;
}
