package org.wso2.ws.dataservice;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.8
 * 2016-11-03T10:32:57.827+01:00
 * Generated source version: 2.7.8
 * 
 */
@WebService(targetNamespace = "http://ws.wso2.org/dataservice", name = "com.crivero.data.servicePortType")
@XmlSeeAlso({ObjectFactory.class})
public interface ComCriveroDataServicePortType {

    @Oneway
    @Action(input = "urn:deleteEmployeeById")
    @RequestWrapper(localName = "deleteEmployeeById", targetNamespace = "http://ws.wso2.org/dataservice", className = "org.wso2.ws.dataservice.DeleteEmployeeById")
    @WebMethod(action = "urn:deleteEmployeeById")
    public void deleteEmployeeById(
        @WebParam(name = "id", targetNamespace = "http://ws.wso2.org/dataservice")
        java.lang.String id
    );

    @WebResult(name = "employee", targetNamespace = "http://ws.wso2.org/dataservice")
    @Action(input = "urn:getEmployees", output = "urn:getEmployeesResponse", fault = {@FaultAction(className = DataServiceFault_Exception.class, value = "urn:getEmployeesDataServiceFault")})
    @RequestWrapper(localName = "getEmployees", targetNamespace = "http://ws.wso2.org/dataservice", className = "org.wso2.ws.dataservice.GetEmployees")
    @WebMethod(action = "urn:getEmployees")
    @ResponseWrapper(localName = "employees", targetNamespace = "http://ws.wso2.org/dataservice", className = "org.wso2.ws.dataservice.Employees")
    public java.util.List<org.wso2.ws.dataservice.Employee> getEmployees() throws DataServiceFault_Exception;

    @Oneway
    @Action(input = "urn:deleteProductById")
    @RequestWrapper(localName = "deleteProductById", targetNamespace = "http://ws.wso2.org/dataservice", className = "org.wso2.ws.dataservice.DeleteProductById")
    @WebMethod(action = "urn:deleteProductById")
    public void deleteProductById(
        @WebParam(name = "id", targetNamespace = "http://ws.wso2.org/dataservice")
        java.lang.String id
    );

    @Oneway
    @Action(input = "urn:insertProduct")
    @RequestWrapper(localName = "insertProduct", targetNamespace = "http://ws.wso2.org/dataservice", className = "org.wso2.ws.dataservice.InsertProduct")
    @WebMethod(action = "urn:insertProduct")
    public void insertProduct(
        @WebParam(name = "id", targetNamespace = "http://ws.wso2.org/dataservice")
        java.lang.String id,
        @WebParam(name = "name", targetNamespace = "http://ws.wso2.org/dataservice")
        java.lang.String name,
        @WebParam(name = "company", targetNamespace = "http://ws.wso2.org/dataservice")
        java.lang.String company
    );

    @WebResult(name = "product", targetNamespace = "http://ws.wso2.org/dataservice")
    @Action(input = "urn:getProducts", output = "urn:getProductsResponse", fault = {@FaultAction(className = DataServiceFault_Exception.class, value = "urn:getProductsDataServiceFault")})
    @RequestWrapper(localName = "getProducts", targetNamespace = "http://ws.wso2.org/dataservice", className = "org.wso2.ws.dataservice.GetProducts")
    @WebMethod(action = "urn:getProducts")
    @ResponseWrapper(localName = "products", targetNamespace = "http://ws.wso2.org/dataservice", className = "org.wso2.ws.dataservice.Products")
    public java.util.List<org.wso2.ws.dataservice.Product> getProducts() throws DataServiceFault_Exception;

    @Oneway
    @Action(input = "urn:insertEmployee")
    @RequestWrapper(localName = "insertEmployee", targetNamespace = "http://ws.wso2.org/dataservice", className = "org.wso2.ws.dataservice.InsertEmployee")
    @WebMethod(action = "urn:insertEmployee")
    public void insertEmployee(
        @WebParam(name = "id", targetNamespace = "http://ws.wso2.org/dataservice")
        java.lang.String id,
        @WebParam(name = "name", targetNamespace = "http://ws.wso2.org/dataservice")
        java.lang.String name,
        @WebParam(name = "address", targetNamespace = "http://ws.wso2.org/dataservice")
        java.lang.String address
    );
}
