
package org.wso2.ws.dataservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.7
 * 2016-10-13T11:53:01.427+02:00
 * Generated source version: 3.1.7
 */

@WebFault(name = "DataServiceFault", targetNamespace = "http://ws.wso2.org/dataservice")
public class DataServiceFault_Exception extends Exception {
    
    private org.wso2.ws.dataservice.DataServiceFault dataServiceFault;

    public DataServiceFault_Exception() {
        super();
    }
    
    public DataServiceFault_Exception(String message) {
        super(message);
    }
    
    public DataServiceFault_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public DataServiceFault_Exception(String message, org.wso2.ws.dataservice.DataServiceFault dataServiceFault) {
        super(message);
        this.dataServiceFault = dataServiceFault;
    }

    public DataServiceFault_Exception(String message, org.wso2.ws.dataservice.DataServiceFault dataServiceFault, Throwable cause) {
        super(message, cause);
        this.dataServiceFault = dataServiceFault;
    }

    public org.wso2.ws.dataservice.DataServiceFault getFaultInfo() {
        return this.dataServiceFault;
    }
}
